import { initializeApp } from "firebase/app"
import { getFirestore, collection, addDoc, Timestamp } from "firebase/firestore"

const firebaseConfig = {
  apiKey: "AIzaSyALwOC0Bk2xUfoTJpGTi-8knQArE1GPdo8",
  authDomain: "ornella-f303f.firebaseapp.com",
  projectId: "ornella-f303f",
  storageBucket: "ornella-f303f.firebasestorage.app",
  messagingSenderId: "659357488733",
  appId: "1:659357488733:web:14daadb13897de75289fb4",
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

const products = [
  // MIRRORS (5 products)
  {
    title: "Vintage Gold Ornate Wall Mirror",
    slug: "vintage-gold-ornate-wall-mirror",
    description: "<p>Transform your space with this stunning vintage-inspired gold ornate wall mirror. Featuring intricate baroque-style detailing and a luxurious gold finish, this mirror adds elegance and sophistication to any room.</p><p>Perfect for entryways, living rooms, or bedrooms, this mirror not only serves a functional purpose but also acts as a beautiful decorative piece. The ornate frame catches light beautifully, creating a warm, inviting atmosphere in your Pakistani home.</p>",
    category: "Mirrors",
    price: 12500,
    stock: 15,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80",
    sku: "ORN-MIR-001",
    weight: 3.5,
    dimensions: "60cm x 80cm",
    material: "Resin frame with glass mirror",
    color: "Antique Gold",
    careInstructions: "Clean with soft, dry cloth. Avoid harsh chemicals. Handle with care to prevent glass breakage.",
    metaTitle: "Vintage Gold Ornate Wall Mirror - Ornella Home Décor",
    metaDescription: "Elevate your home with our vintage gold ornate wall mirror. Baroque-style detailing, luxurious finish. Perfect for Pakistani homes. Shop now at Ornella.",
    keywords: ["ornate mirror", "gold mirror", "vintage mirror", "wall mirror Pakistan", "decorative mirror", "baroque mirror"],
    altText: "Vintage gold ornate baroque-style wall mirror with intricate frame detailing",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Modern Round Black Frame Mirror",
    slug: "modern-round-black-frame-mirror",
    description: "<p>Embrace contemporary design with this sleek modern round black frame mirror. The minimalist aesthetic and clean lines make it a versatile addition to any modern Pakistani home.</p><p>This mirror features a powder-coated matte black metal frame that complements various interior styles. Ideal for hallways, bathrooms, or as part of a gallery wall arrangement.</p>",
    category: "Mirrors",
    price: 7500,
    stock: 25,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1595514535116-9e0d3d6e8a3d?w=800&q=80",
    sku: "ORN-MIR-002",
    weight: 2.2,
    dimensions: "50cm diameter",
    material: "Metal frame with glass mirror",
    color: "Matte Black",
    careInstructions: "Wipe with damp cloth. Dry immediately. Avoid abrasive cleaners.",
    metaTitle: "Modern Round Black Frame Mirror - Minimalist Design | Ornella",
    metaDescription: "Shop our modern round black frame mirror. Sleek minimalist design perfect for contemporary Pakistani homes. Quality craftsmanship. Free delivery.",
    keywords: ["round mirror", "black frame mirror", "modern mirror", "minimalist mirror", "contemporary decor", "wall mirror"],
    altText: "Modern round wall mirror with sleek matte black metal frame",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Full Length Standing Floor Mirror",
    slug: "full-length-standing-floor-mirror",
    description: "<p>Check your complete outfit with this elegant full-length standing floor mirror. Featuring a sturdy wooden frame and adjustable angle, this mirror is both functional and stylish.</p><p>The warm walnut finish adds a touch of sophistication to bedrooms or dressing areas. The mirror can be tilted to achieve the perfect viewing angle, making it ideal for daily use.</p>",
    category: "Mirrors",
    price: 18900,
    stock: 10,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80",
    sku: "ORN-MIR-003",
    weight: 8.5,
    dimensions: "45cm x 160cm",
    material: "Solid wood frame with glass mirror",
    color: "Walnut Brown",
    careInstructions: "Clean glass with streak-free cleaner. Dust wooden frame regularly. Ensure stable placement on flat surface.",
    metaTitle: "Full Length Standing Floor Mirror - Walnut Frame | Ornella",
    metaDescription: "Premium full-length standing floor mirror with walnut frame. Adjustable tilt, sturdy design. Perfect for bedrooms in Pakistan. Order online today.",
    keywords: ["full length mirror", "floor mirror", "standing mirror", "bedroom mirror", "dressing mirror", "wooden frame mirror"],
    altText: "Full-length standing floor mirror with elegant walnut wooden frame",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Rustic Wooden Arched Mirror",
    slug: "rustic-wooden-arched-mirror",
    description: "<p>Add warmth and character to your home with this beautiful rustic wooden arched mirror. The natural wood grain and arched design create a farmhouse-chic aesthetic that's trending in modern Pakistani interiors.</p><p>Handcrafted with attention to detail, this mirror brings organic texture and visual interest to any wall. Perfect for creating a focal point in living rooms or entryways.</p>",
    category: "Mirrors",
    price: 14500,
    stock: 12,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1625527575307-616f0f5c5ad7?w=800&q=80",
    sku: "ORN-MIR-004",
    weight: 4.0,
    dimensions: "55cm x 90cm",
    material: "Natural wood frame with glass mirror",
    color: "Natural Oak",
    careInstructions: "Wipe with slightly damp cloth. Apply wood polish occasionally. Keep away from direct moisture.",
    metaTitle: "Rustic Wooden Arched Mirror - Farmhouse Style | Ornella",
    metaDescription: "Handcrafted rustic wooden arched mirror for your home. Natural oak finish, farmhouse design. Premium quality. Shop Ornella Pakistan.",
    keywords: ["arched mirror", "rustic mirror", "wooden mirror", "farmhouse decor", "natural wood mirror", "handcrafted mirror"],
    altText: "Rustic handcrafted arched mirror with natural oak wooden frame",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Geometric Hexagon Mirror Set",
    slug: "geometric-hexagon-mirror-set",
    description: "<p>Create a stunning gallery wall with this set of 7 geometric hexagon mirrors. The modern design and versatile arrangement options make this set perfect for adding depth and dimension to any space.</p><p>Each hexagon can be arranged in multiple patterns, allowing you to customize the look to match your interior style. The frameless design keeps the focus on the reflective surfaces, creating an airy, contemporary feel.</p>",
    category: "Mirrors",
    price: 9800,
    stock: 18,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&q=80",
    sku: "ORN-MIR-005",
    weight: 1.8,
    dimensions: "Each hexagon: 15cm x 17cm",
    material: "Frameless glass mirrors",
    color: "Clear Mirror",
    careInstructions: "Clean with glass cleaner. Install securely with provided adhesive pads. Handle individual pieces carefully.",
    metaTitle: "Geometric Hexagon Mirror Set (7pcs) - Modern Wall Décor",
    metaDescription: "7-piece geometric hexagon mirror set for stunning wall displays. Frameless design, customizable arrangement. Modern home décor Pakistan. Buy now.",
    keywords: ["hexagon mirror", "geometric mirror set", "mirror wall art", "modern decor", "frameless mirror", "gallery wall"],
    altText: "Set of seven geometric hexagon frameless mirrors for modern wall display",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },

  // LIGHTING (5 products)
  {
    title: "Industrial Pendant Light with Edison Bulb",
    slug: "industrial-pendant-light-edison-bulb",
    description: "<p>Illuminate your space with vintage charm using this industrial pendant light featuring an authentic Edison bulb. The exposed bulb design and metal cage create an urban, loft-style ambiance perfect for modern Pakistani homes.</p><p>Ideal for kitchen islands, dining areas, or as accent lighting in living rooms. The adjustable cord length allows for customized installation height.</p>",
    category: "Lighting",
    price: 6500,
    stock: 20,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1565118531796-763e5082d113?w=800&q=80",
    sku: "ORN-LIT-001",
    weight: 1.2,
    dimensions: "Shade: 20cm diameter, Cord: 150cm adjustable",
    material: "Metal cage with fabric cord",
    color: "Matte Black with Bronze accents",
    careInstructions: "Dust regularly. Turn off power before cleaning. Replace bulb with same wattage (40W Edison bulb included).",
    metaTitle: "Industrial Pendant Light with Edison Bulb - Vintage Style",
    metaDescription: "Vintage industrial pendant light with Edison bulb. Metal cage design, adjustable cord. Perfect for modern Pakistani homes. Shop Ornella lighting.",
    keywords: ["pendant light", "Edison bulb light", "industrial lighting", "vintage light fixture", "hanging light Pakistan", "kitchen lighting"],
    altText: "Industrial-style pendant light fixture with Edison bulb and metal cage",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Crystal Chandelier with LED Lights",
    slug: "crystal-chandelier-led-lights",
    description: "<p>Add luxury and elegance to your dining room or foyer with this stunning crystal chandelier. Featuring energy-efficient LED lights and premium crystal drops, this fixture creates beautiful light reflections throughout the room.</p><p>The modern design combines classic chandelier aesthetics with contemporary LED technology, providing both beauty and practicality for Pakistani homes.</p>",
    category: "Lighting",
    price: 28500,
    stock: 8,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80",
    sku: "ORN-LIT-002",
    weight: 6.5,
    dimensions: "60cm diameter x 70cm height",
    material: "Stainless steel frame with K9 crystal drops",
    color: "Chrome with Clear Crystal",
    careInstructions: "Clean crystals with soft cloth. Avoid water. Professional installation recommended. LED bulbs included.",
    metaTitle: "Crystal Chandelier with LED Lights - Luxury Home Lighting",
    metaDescription: "Elegant crystal chandelier with energy-efficient LED lights. Premium K9 crystal, chrome finish. Transform your Pakistani home. Order online.",
    keywords: ["crystal chandelier", "LED chandelier", "luxury lighting", "dining room chandelier", "elegant light fixture", "ceiling light Pakistan"],
    altText: "Elegant crystal chandelier with LED lights and chrome finish",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Modern Arc Floor Lamp",
    slug: "modern-arc-floor-lamp",
    description: "<p>This contemporary arc floor lamp combines style and functionality, providing overhead lighting without ceiling installation. The sweeping curved design and marble base create a sophisticated focal point in any room.</p><p>Perfect for reading corners, beside sofas, or as ambient lighting in living rooms. The adjustable arm allows you to direct light exactly where needed.</p>",
    category: "Lighting",
    price: 16500,
    stock: 12,
    features: false,
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
    sku: "ORN-LIT-003",
    weight: 8.0,
    dimensions: "Base: 30cm diameter, Height: 180cm, Reach: 150cm",
    material: "Brushed steel with marble base",
    color: "Brushed Gold with White Marble",
    careInstructions: "Wipe with dry cloth. Clean marble base with damp cloth only. Ensure stable placement. 60W bulb recommended.",
    metaTitle: "Modern Arc Floor Lamp - Gold & Marble Design | Ornella",
    metaDescription: "Contemporary arc floor lamp with marble base. Brushed gold finish, adjustable arm. Premium quality lighting for Pakistani homes. Buy now.",
    keywords: ["arc floor lamp", "modern floor lamp", "standing lamp", "reading lamp", "marble lamp", "gold floor lamp"],
    altText: "Modern arc floor lamp with brushed gold finish and white marble base",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Moroccan Brass Table Lamp",
    slug: "moroccan-brass-table-lamp",
    description: "<p>Infuse your space with exotic charm using this handcrafted Moroccan brass table lamp. The intricate perforated design casts enchanting light patterns on surrounding walls, creating a warm, ambient atmosphere.</p><p>Each lamp is carefully crafted by skilled artisans, making every piece unique. Perfect for bedside tables, console tables, or as accent lighting in living areas.</p>",
    category: "Lighting",
    price: 8900,
    stock: 15,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&q=80",
    sku: "ORN-LIT-004",
    weight: 2.5,
    dimensions: "25cm diameter x 35cm height",
    material: "Handcrafted brass with fabric cord",
    color: "Antique Brass",
    careInstructions: "Wipe with soft dry cloth. Polish occasionally with brass cleaner. Keep away from moisture. 40W bulb included.",
    metaTitle: "Handcrafted Moroccan Brass Table Lamp - Artisan Lighting",
    metaDescription: "Authentic Moroccan brass table lamp with intricate patterns. Handcrafted, creates beautiful light effects. Unique home décor Pakistan. Shop Ornella.",
    keywords: ["Moroccan lamp", "brass table lamp", "handcrafted lamp", "bedside lamp", "ethnic lighting", "decorative lamp Pakistan"],
    altText: "Handcrafted Moroccan brass table lamp with intricate perforated patterns",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Minimalist LED Strip Wall Sconce",
    slug: "minimalist-led-strip-wall-sconce",
    description: "<p>Achieve modern elegance with this minimalist LED strip wall sconce. The sleek linear design provides ambient lighting while serving as a contemporary art piece on your wall.</p><p>Energy-efficient LED technology ensures long-lasting performance with minimal power consumption. Perfect for hallways, bedrooms, or as accent lighting in modern Pakistani interiors.</p>",
    category: "Lighting",
    price: 5500,
    stock: 30,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1550684376-efcbd6e3f031?w=800&q=80",
    sku: "ORN-LIT-005",
    weight: 0.8,
    dimensions: "60cm length x 5cm width x 3cm depth",
    material: "Aluminum with acrylic diffuser",
    color: "Matte White",
    careInstructions: "Wipe with damp cloth. Integrated LED (non-replaceable, 50,000 hour lifespan). Professional installation recommended.",
    metaTitle: "Minimalist LED Strip Wall Sconce - Modern Lighting",
    metaDescription: "Sleek minimalist LED wall sconce for modern homes. Energy-efficient, contemporary design. Perfect accent lighting Pakistan. Free shipping.",
    keywords: ["LED wall sconce", "minimalist lighting", "wall light", "modern sconce", "hallway lighting", "LED strip light"],
    altText: "Minimalist LED strip wall sconce with sleek white aluminum finish",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },

  // WALL ART (5 products)
  {
    title: "Abstract Geometric Canvas Art Set (3 Pieces)",
    slug: "abstract-geometric-canvas-art-set-3-pieces",
    description: "<p>Transform your walls with this stunning 3-piece abstract geometric canvas art set. The contemporary design features bold shapes and a sophisticated color palette that complements modern Pakistani interiors.</p><p>Printed on premium canvas with fade-resistant inks, each piece is gallery-wrapped and ready to hang. Perfect for living rooms, offices, or as a statement piece in bedrooms.</p>",
    category: "Wall Art",
    price: 11500,
    stock: 20,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800&q=80",
    sku: "ORN-ART-001",
    weight: 2.0,
    dimensions: "Each panel: 40cm x 60cm",
    material: "Canvas on wooden frame",
    color: "Navy Blue, Gold, and Cream",
    careInstructions: "Dust with soft dry cloth. Avoid direct sunlight to prevent fading. Do not use water or chemicals.",
    metaTitle: "Abstract Geometric Canvas Art Set (3pcs) - Modern Wall Décor",
    metaDescription: "3-piece abstract geometric canvas art set. Premium quality, ready to hang. Modern design for Pakistani homes. Shop Ornella wall art collection.",
    keywords: ["canvas art", "geometric art", "abstract painting", "3 piece wall art", "modern wall decor", "living room art Pakistan"],
    altText: "Three-piece abstract geometric canvas art set in navy blue, gold and cream tones",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Islamic Calligraphy Gold Foil Print",
    slug: "islamic-calligraphy-gold-foil-print",
    description: "<p>Bring spiritual elegance to your home with this exquisite Islamic calligraphy print featuring real gold foil detailing. The beautiful Arabic script is rendered in a contemporary style that honors tradition while embracing modern design.</p><p>Perfect for prayer rooms, living areas, or as meaningful gifts. The black and gold color scheme adds sophistication to any space in your Pakistani home.</p>",
    category: "Wall Art",
    price: 7500,
    stock: 25,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1578301978018-3005759f48f7?w=800&q=80",
    sku: "ORN-ART-002",
    weight: 1.0,
    dimensions: "50cm x 70cm",
    material: "Premium paper with gold foil on black frame",
    color: "Gold on Black",
    careInstructions: "Frame with glass protection. Keep away from moisture. Dust frame gently. Avoid direct sunlight.",
    metaTitle: "Islamic Calligraphy Gold Foil Print - Arabic Wall Art",
    metaDescription: "Elegant Islamic calligraphy with real gold foil. Contemporary design, premium quality. Perfect for Pakistani homes. Order online at Ornella.",
    keywords: ["Islamic calligraphy", "Arabic wall art", "gold foil print", "religious art", "Muslim home decor", "calligraphy Pakistan"],
    altText: "Islamic Arabic calligraphy print with gold foil on black background",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Botanical Leaf Prints Set (4 Pieces)",
    slug: "botanical-leaf-prints-set-4-pieces",
    description: "<p>Bring the beauty of nature indoors with this elegant 4-piece botanical leaf print set. The minimalist design and soft green tones create a calming, organic atmosphere in any room.</p><p>Each print features high-quality reproductions of tropical leaves, perfect for adding a fresh, natural element to your décor. Ideal for bedrooms, bathrooms, or creating a gallery wall.</p>",
    category: "Wall Art",
    price: 6800,
    stock: 18,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&q=80",
    sku: "ORN-ART-003",
    weight: 1.5,
    dimensions: "Each print: 30cm x 40cm",
    material: "Art paper in white wooden frames",
    color: "Green and White",
    careInstructions: "Wipe frames with damp cloth. Keep prints protected under glass. Avoid humid areas.",
    metaTitle: "Botanical Leaf Prints Set (4pcs) - Nature Wall Art | Ornella",
    metaDescription: "4-piece botanical leaf print set for natural home décor. Minimalist design, calming green tones. Perfect for Pakistani homes. Shop now.",
    keywords: ["botanical prints", "leaf art", "nature wall art", "tropical prints", "green wall decor", "minimalist art Pakistan"],
    altText: "Four botanical leaf prints in white frames showing various tropical leaves",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Vintage Pakistan Map Print",
    slug: "vintage-pakistan-map-print",
    description: "<p>Celebrate Pakistani heritage with this beautifully designed vintage-style map print. The detailed cartography and muted color palette give it an antique aesthetic that adds character to any space.</p><p>A perfect conversation piece for offices, studies, or living rooms. This print showcases Pakistan's geography with artistic flair, making it both decorative and educational.</p>",
    category: "Wall Art",
    price: 4500,
    stock: 30,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=800&q=80",
    sku: "ORN-ART-004",
    weight: 0.8,
    dimensions: "60cm x 80cm",
    material: "Premium matte paper with wooden frame",
    color: "Sepia and Cream",
    careInstructions: "Frame under glass for protection. Dust frame regularly. Keep away from direct moisture.",
    metaTitle: "Vintage Pakistan Map Print - Heritage Wall Art | Ornella",
    metaDescription: "Vintage-style Pakistan map print with antique aesthetic. Perfect for offices and homes. Celebrate Pakistani heritage. Order online.",
    keywords: ["Pakistan map", "vintage map print", "heritage art", "Pakistan wall art", "map poster", "patriotic decor"],
    altText: "Vintage-style map print of Pakistan with antique sepia tones and detailed cartography",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Metallic Sunset Landscape Canvas",
    slug: "metallic-sunset-landscape-canvas",
    description: "<p>Capture the breathtaking beauty of a sunset with this metallic landscape canvas. The special printing technique includes metallic inks that catch light, creating a shimmering effect that changes throughout the day.</p><p>The warm tones and tranquil scene bring a sense of peace and natural beauty to your space. Perfect as a focal point in living rooms or bedrooms.</p>",
    category: "Wall Art",
    price: 13500,
    stock: 10,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800&q=80",
    sku: "ORN-ART-005",
    weight: 2.5,
    dimensions: "90cm x 60cm",
    material: "Canvas with metallic ink on wooden stretcher",
    color: "Orange, Purple, and Gold",
    careInstructions: "Clean gently with dry microfiber cloth. Avoid touching canvas surface. Keep away from direct sunlight for longevity.",
    metaTitle: "Metallic Sunset Landscape Canvas - Shimmering Wall Art",
    metaDescription: "Stunning sunset landscape canvas with metallic inks. Light-reflective, premium quality. Transform your Pakistani home. Shop Ornella art.",
    keywords: ["sunset canvas", "metallic wall art", "landscape painting", "shimmering art", "large canvas art", "living room decor Pakistan"],
    altText: "Landscape canvas print of colorful sunset with metallic shimmering effect",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },

  // VASES & POTS (5 products)
  {
    title: "Ceramic Minimalist White Vase Set (3 Sizes)",
    slug: "ceramic-minimalist-white-vase-set-3-sizes",
    description: "<p>Elevate your home styling with this elegant set of three minimalist white ceramic vases. The clean lines and varying heights create visual interest and versatility for different floral arrangements.</p><p>Perfect for fresh or dried flowers, or simply as standalone decorative pieces. The matte white finish complements any interior color scheme and adds a touch of Scandinavian-inspired elegance to Pakistani homes.</p>",
    category: "Vases & Pots",
    price: 5500,
    stock: 22,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=800&q=80",
    sku: "ORN-VAS-001",
    weight: 2.8,
    dimensions: "Small: 10cm, Medium: 15cm, Large: 20cm height",
    material: "Glazed ceramic",
    color: "Matte White",
    careInstructions: "Hand wash with mild soap. Not dishwasher safe. Handle with care to avoid chips. Waterproof for fresh flowers.",
    metaTitle: "Ceramic Minimalist White Vase Set (3pcs) - Modern Home Décor",
    metaDescription: "Set of 3 minimalist white ceramic vases in varying sizes. Clean design, versatile styling. Perfect for Pakistani homes. Shop Ornella vases.",
    keywords: ["white vase", "ceramic vase set", "minimalist vase", "decorative vase", "home accessories Pakistan", "Scandinavian decor"],
    altText: "Set of three minimalist white ceramic vases in small, medium and large sizes",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Terracotta Indoor Plant Pot with Saucer",
    slug: "terracotta-indoor-plant-pot-saucer",
    description: "<p>Bring natural warmth to your indoor garden with this handcrafted terracotta plant pot. The porous material allows roots to breathe while the classic design suits both modern and traditional Pakistani homes.</p><p>Includes matching saucer to protect surfaces from water. Perfect for succulents, herbs, or small houseplants. The earthy terracotta color develops a beautiful patina over time.</p>",
    category: "Vases & Pots",
    price: 1800,
    stock: 40,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80",
    sku: "ORN-VAS-002",
    weight: 1.5,
    dimensions: "18cm diameter x 16cm height",
    material: "Natural terracotta clay",
    color: "Natural Terracotta Orange",
    careInstructions: "Soak in water before first use. Drainage hole included. May develop white salt deposits (normal for terracotta). Clean with brush.",
    metaTitle: "Terracotta Indoor Plant Pot with Saucer - Natural Clay",
    metaDescription: "Handcrafted terracotta plant pot for indoor plants. Natural clay, includes saucer. Perfect for Pakistani homes. Buy planters online.",
    keywords: ["terracotta pot", "plant pot", "indoor planter", "clay pot", "succulent pot", "houseplant container Pakistan"],
    altText: "Natural terracotta clay plant pot with matching saucer for indoor plants",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Blue and White Porcelain Ginger Jar",
    slug: "blue-white-porcelain-ginger-jar",
    description: "<p>Add timeless elegance to your décor with this classic blue and white porcelain ginger jar. Featuring intricate hand-painted patterns, this decorative piece brings a touch of chinoiserie charm to any room.</p><p>Perfect for displaying on mantels, bookshelves, or as a centerpiece. The traditional design with contemporary styling makes it a versatile accent piece for Pakistani homes.</p>",
    category: "Vases & Pots",
    price: 8900,
    stock: 15,
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&q=80",
    sku: "ORN-VAS-003",
    weight: 2.0,
    dimensions: "22cm diameter x 28cm height",
    material: "Fine porcelain with hand-painted glaze",
    color: "Blue and White",
    careInstructions: "Wipe with soft damp cloth. Not suitable for fresh flowers (decorative only). Handle with care due to delicate material.",
    metaTitle: "Blue & White Porcelain Ginger Jar - Classic Home Décor",
    metaDescription: "Hand-painted blue and white porcelain ginger jar. Timeless chinoiserie design. Elegant home accent for Pakistan. Shop Ornella.",
    keywords: ["ginger jar", "porcelain vase", "blue and white", "chinoiserie decor", "decorative jar", "classic home accessories"],
    altText: "Blue and white porcelain ginger jar with intricate hand-painted traditional patterns",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Modern Geometric Concrete Planter",
    slug: "modern-geometric-concrete-planter",
    description: "<p>Make a bold statement with this modern geometric concrete planter. The industrial aesthetic and unique angular design add contemporary edge to your plant display.</p><p>Handcrafted from high-quality concrete with a smooth finish. The heavy, stable base ensures your plants stay secure. Ideal for succulents, cacti, or small foliage plants in modern Pakistani interiors.</p>",
    category: "Vases & Pots",
    price: 3500,
    stock: 28,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=800&q=80",
    sku: "ORN-VAS-004",
    weight: 3.2,
    dimensions: "15cm x 15cm x 12cm",
    material: "Sealed concrete",
    color: "Light Gray",
    careInstructions: "Drainage hole included. Seal periodically to maintain finish. Wipe clean with damp cloth. Heavy - place carefully.",
    metaTitle: "Modern Geometric Concrete Planter - Industrial Design",
    metaDescription: "Handcrafted geometric concrete planter for modern homes. Industrial style, durable material. Perfect for succulents. Shop Ornella Pakistan.",
    keywords: ["concrete planter", "geometric pot", "modern planter", "industrial decor", "succulent pot", "cement planter Pakistan"],
    altText: "Modern geometric concrete planter with angular design in light gray finish",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
  {
    title: "Brass Hammered Metal Flower Vase",
    slug: "brass-hammered-metal-flower-vase",
    description: "<p>Add metallic glamour to your space with this stunning brass hammered metal flower vase. The hand-hammered texture catches light beautifully, creating visual interest from every angle.</p><p>The warm brass tone complements both traditional and contemporary décor styles. Perfect for displaying fresh or dried flower arrangements, or as a standalone sculptural piece in Pakistani homes.</p>",
    category: "Vases & Pots",
    price: 6500,
    stock: 18,
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1565192034370-c8e37f93c4df?w=800&q=80",
    sku: "ORN-VAS-005",
    weight: 1.8,
    dimensions: "12cm diameter x 25cm height",
    material: "Hammered brass metal with waterproof liner",
    color: "Antique Brass Gold",
    careInstructions: "Wipe with soft cloth. Polish with brass cleaner to maintain shine. Waterproof liner allows fresh flowers. Do not submerge in water.",
    metaTitle: "Brass Hammered Metal Flower Vase - Luxury Home Décor",
    metaDescription: "Hand-hammered brass metal vase with waterproof liner. Luxurious gold finish. Perfect for flowers and home styling Pakistan. Buy online.",
    keywords: ["brass vase", "metal vase", "hammered vase", "gold vase", "luxury home decor", "flower vase Pakistan"],
    altText: "Hand-hammered brass metal flower vase with antique gold finish and textured surface",
    status: "active",
    createdAt: Timestamp.now(),
    updatedAt: Timestamp.now(),
  },
]

async function populateProducts() {
  try {
    console.log("🚀 Starting to populate products...")
    console.log(`📦 Total products to add: ${products.length}`)
    
    let successCount = 0
    let errorCount = 0

    for (const product of products) {
      try {
        const docRef = await addDoc(collection(db, "products"), product)
        successCount++
        console.log(`✅ Added: ${product.title} (ID: ${docRef.id})`)
      } catch (error) {
        errorCount++
        console.error(`❌ Failed to add ${product.title}:`, error)
      }
    }

    console.log("\n" + "=".repeat(60))
    console.log("📊 SUMMARY")
    console.log("=".repeat(60))
    console.log(`✅ Successfully added: ${successCount} products`)
    console.log(`❌ Failed: ${errorCount} products`)
    console.log("\n🎉 Product population complete!")
    console.log("🌐 Visit http://localhost:3000/admin/products to view your products")
  } catch (error) {
    console.error("💥 Fatal error during population:", error)
  }
}

populateProducts()
